remote_theme: pages-themes/architect@v0.2.0

title: [Anna Romanova / Романова Анна Сергеевна]
description: [AI Visionary & Corporate Leader | Building Autonomous Governance Systems | TRIUM Global EMBA | Author | Speaker]
description: [Email | SSRN |]
