remote_theme: pages-themes/architect@v0.2.0

title: [Anna Romanova / Романова Анна Сергеевна]
description: [[Email](anna.romanova@stern.nyu.edu) | [Linkedin](https://www.linkedin.com/in/romanovaanna/) | ORCID | SSRN | Arxiv | ResearchGate | GitHub | Blog]
